# Generated by Django 6.1.1 on 2026-09-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('preferred_date', models.CharField(max_length=50)),
                ('preferred_time', models.CharField(max_length=50)),
                ('guest_count', models.IntegerField(default=1)),
                ('pet_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pet_breed', models.CharField(blank=True, max_length=100, null=True)),
                ('service_interest', models.CharField(default='private_walkthrough', max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='confirmed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'showroom_appointments',
                'ordering': ['-created_at'],
            },
        ),
    ]
