# Generated by Django 5.2.17 on 2026-09-15 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cart', '0001_initial'),
        ('products', '0004_product_alt_text_product_barcode_product_bestseller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_user_cart_product_variant',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
