# Generated by Django 6.1.1 on 2026-09-09 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_code', models.CharField(db_index=True, help_text='Example: DSG-001', max_length=30, unique=True, verbose_name='Designer Code')),
                ('designer_name', models.CharField(max_length=255, verbose_name='Designer Name')),
                ('brand_name', models.CharField(max_length=255, verbose_name='Brand')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Owner Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Phone')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('primary_category', models.CharField(help_text='Example: Pet Occasion Wear', max_length=150, verbose_name='Primary Category')),
                ('tier', models.CharField(choices=[('CORE', 'Core'), ('PREMIUM', 'Premium'), ('EMERGING', 'Emerging')], default='EMERGING', max_length=30, verbose_name='Designer Tier')),
                ('take_rate', models.DecimalField(decimal_places=2, default=0, help_text='Platform commission percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Take Rate (%)')),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GST number.', regex='^[0-9A-Z]{15}$')], verbose_name='GST Number')),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20, verbose_name='KYC Status')),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='KYC Verified At')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='Contract Start Date')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Contract End Date')),
                ('contract_signed', models.BooleanField(default=False, verbose_name='Contract Signed')),
                ('stage', models.CharField(choices=[('LEAD', 'Lead'), ('QUALIFIED', 'Qualified'), ('PORTFOLIO', 'Portfolio'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('CONTRACT', 'Contract'), ('SIGNED', 'Signed'), ('LIVE', 'Live'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive')], db_index=True, default='LEAD', max_length=30, verbose_name='Pipeline Stage')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='designers/logos/', verbose_name='Brand Logo')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='designers/profiles/', verbose_name='Profile Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Designer Description')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Designer',
                'verbose_name_plural': 'Designers',
                'db_table': 'designer',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['designer_code'], name='designer_designe_739057_idx'), models.Index(fields=['brand_name'], name='designer_brand_n_a5e307_idx'), models.Index(fields=['city'], name='designer_city_71653a_idx'), models.Index(fields=['primary_category'], name='designer_primary_897a0c_idx'), models.Index(fields=['stage'], name='designer_stage_8beedf_idx'), models.Index(fields=['kyc_status'], name='designer_kyc_sta_3ad809_idx'), models.Index(fields=['tier'], name='designer_tier_756348_idx'), models.Index(fields=['is_active'], name='designer_is_acti_0d063b_idx')],
            },
        ),
    ]
