# Generated by Django 6.1.1 on 2026-09-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('read_time', models.CharField(default='4 min read', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('content', models.JSONField(default=list)),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('author', models.CharField(default='Zenve Editorial', max_length=150)),
                ('published_at', models.CharField(default='', max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'journal_articles',
                'ordering': ['-id'],
            },
        ),
    ]
