# Generated by Django 6.1.1 on 2026-09-10 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_status_407ffb_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_designe_7bc7f7_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='atelier_pick',
            field=models.BooleanField(default=False, verbose_name='Atelier Pick'),
        ),
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Care Instructions'),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Collection'),
        ),
        migrations.AddField(
            model_name='product',
            name='collection_slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Collection Slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, verbose_name='Colors [{name, hex}]'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='Images List'),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Occasion'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=5.0, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Review Count'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list, verbose_name='Sizes List'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Primary Colour'),
        ),
        migrations.AlterField(
            model_name='product',
            name='designer',
            field=models.CharField(blank=True, default='Zenve Atelier', max_length=255, verbose_name='Designer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fast_delivery',
            field=models.BooleanField(default=True, verbose_name='Fast Delivery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fulfilment_location',
            field=models.CharField(choices=[('MUMBAI_FC', 'Mumbai FC'), ('BANGALORE_FC', 'Bangalore FC'), ('DELHI_FC', 'Delhi FC'), ('DESIGNER_STUDIO', 'Designer Studio')], default='MUMBAI_FC', max_length=100, verbose_name='Fulfilment Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_quantity',
            field=models.PositiveIntegerField(default=10, verbose_name='Inventory Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_live',
            field=models.BooleanField(default=True, verbose_name='Live on Storefront'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='MRP / Original Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_QA', 'Pending QA'), ('APPROVED', 'Approved'), ('LIVE', 'Live'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive')], db_index=True, default='LIVE', max_length=30, verbose_name='Product Status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='product_slug_b8980b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['collection_slug'], name='product_collect_d0fb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['occasion'], name='product_occasio_09f8af_idx'),
        ),
    ]
