# Generated by Django 6.1.1 on 2026-09-11 05:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0001_initial'),
        ('products', '0002_remove_product_product_status_407ffb_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_slug_b8980b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_collect_d0fb2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_occasio_09f8af_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='damaged_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Damaged Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_transit_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='In-Transit Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='qa_score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='QA Score'),
        ),
        migrations.AddField(
            model_name='product',
            name='quarantined_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quarantined Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Reserved Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Returned Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=150, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='product',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='designers.designer', verbose_name='Designer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fast_delivery',
            field=models.BooleanField(default=False, verbose_name='Fast Delivery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fulfilment_location',
            field=models.CharField(choices=[('MUMBAI_FC', 'Mumbai FC'), ('BANGALORE_FC', 'Bangalore FC'), ('DELHI_FC', 'Delhi FC'), ('DESIGNER_STUDIO', 'Designer Studio')], max_length=100, verbose_name='Fulfilment Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Physical Inventory Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='Live on Storefront'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='MRP'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_QA', 'Pending QA'), ('CORRECTION', 'Needs Correction'), ('APPROVED', 'Approved'), ('LIVE', 'Live'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive')], db_index=True, default='DRAFT', max_length=30, verbose_name='Product Status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='product_status_407ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['designer'], name='product_designe_7335c5_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='atelier_pick',
        ),
        migrations.RemoveField(
            model_name='product',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='product',
            name='care_instructions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='product',
            name='collection_slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='occasion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subtitle',
        ),
    ]
