from decimal import Decimal
from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from accounts.models import Role, UserRole, Customer, CustomerAddress
from products.models import Product
from zenve_collections.models import Collection
from journal.models import Article


class Command(BaseCommand):
    help = "Seed Zenve Fashion Atelier catalog, collections, editorial journal, and test accounts."

    def handle(self, *args, **options):
        self.stdout.write(self.style.NOTICE("Seeding Zenve Fashion Atelier database..."))

        # ----------------------------------------------------
        # 1. ROLES & TEST USERS
        # ----------------------------------------------------
        cust_role, _ = Role.objects.get_or_create(
            name="Customer", defaults={"description": "Standard atelier client"}
        )
        admin_role, _ = Role.objects.get_or_create(
            name="Admin", defaults={"description": "Atelier administrator"}
        )

        # Test customer
        cust_user, created = User.objects.get_or_create(
            email="customer@zenve.fashion",
            defaults={
                "username": "zenve_client",
                "first_name": "Aarav",
                "last_name": "Mehta",
                "is_active": True,
            },
        )
        if created:
            cust_user.set_password("zenvePass2026!")
            cust_user.save()
            UserRole.objects.get_or_create(user=cust_user, defaults={"role": cust_role})
            customer_profile, _ = Customer.objects.get_or_create(
                user=cust_user,
                defaults={"phone_number": "9876543210", "city": "Bengaluru", "country": "India"},
            )
            CustomerAddress.objects.get_or_create(
                customer=customer_profile,
                full_name="Aarav Mehta",
                phone_number="9876543210",
                address_line1="Villa 14, 4th Block, Jayanagar",
                address_line2="Near Ashoka Pillar",
                city="Bengaluru",
                state="Karnataka",
                country="India",
                postal_code="560011",
                is_default=True,
            )

        # Admin user
        admin_user, a_created = User.objects.get_or_create(
            email="admin@zenve.fashion",
            defaults={
                "username": "atelier_admin",
                "first_name": "Zenve",
                "last_name": "Director",
                "is_staff": True,
                "is_superuser": True,
                "is_active": True,
            },
        )
        if a_created:
            admin_user.set_password("zenveAdmin2026!")
            admin_user.save()
            UserRole.objects.get_or_create(user=admin_user, defaults={"role": admin_role})

        # ----------------------------------------------------
        # 2. COLLECTIONS
        # ----------------------------------------------------
        collections_data = [
            {
                "name": "The Nocturne Velvet Edit",
                "slug": "nocturne-velvet",
                "description": "Bespoke midnight velvets, structured silhouettes, and molten gold zari accents.",
                "image": "/images/collections/people.jpg",
                "category": "people",
                "item_count": 22,
            },
            {
                "name": "The Imperial Pet Suite",
                "slug": "imperial-pet-suite",
                "description": "Ergonomically tailored outerwear crafted in silk brocades and hypoallergenic cashmeres.",
                "image": "/images/collections/pets.jpg",
                "category": "pets",
                "item_count": 20,
            },
            {
                "name": "The Twin Edit Atelier",
                "slug": "twin-edit-atelier",
                "description": "Harmonious coordinated ensembles designed in tandem for client and companion.",
                "image": "/images/collections/twin.jpg",
                "category": "twin",
                "item_count": 15,
            },
            {
                "name": "Royal Heritage Regalia",
                "slug": "royal-heritage-regalia",
                "description": "Heirloom craftsmanship, real silver zari work, and royal ceremonial tailoring.",
                "image": "/images/collections/collections-hero-banner.png",
                "category": "all",
                "item_count": 30,
            },
            {
                "name": "Festive Zari & Brocade",
                "slug": "festive-zari-brocade",
                "description": "Rich jewel-toned brocades and celebratory occasionwear made for grand celebrations.",
                "image": "/images/collections/shop-banner-clean.png",
                "category": "all",
                "item_count": 25,
            },
        ]

        for c in collections_data:
            Collection.objects.update_or_create(
                slug=c["slug"],
                defaults={
                    "name": c["name"],
                    "description": c["description"],
                    "image": c["image"],
                    "category": c["category"],
                    "item_count": c["item_count"],
                },
            )

        # ----------------------------------------------------
        # 3. JOURNAL ARTICLES
        # ----------------------------------------------------
        journal_data = [
            {
                "slug": "craftsmanship-behind-zari",
                "title": "The Craftsmanship Behind Handwoven Zari",
                "category": "FABRIC",
                "read_time": "5 MIN",
                "description": "Exploring the centuries-old metallurgical artistry of real silver wire woven into mulberry silk.",
                "content": [
                    "In our Bengaluru atelier, zari is treated not merely as decoration, but as an architectural discipline. Real silver electroplated with 24-karat gold is drawn into micronic filaments before being interlocked with raw silk warp threads.",
                    "The result is a textile that catches twilight differently than synthetic lamé — a deep, liquid glow that softens with time rather than tarnishing.",
                    "Each meter requires between 40 to 60 hours of loom time, ensuring an heirloom weight that drapes effortlessly over both human shoulder and companion torso."
                ],
                "image": "/images/journal/craftsmanship-behind-zari.jpg",
                "author": "Maheshwara Rao, Master Weaver",
                "published_at": "2026-03-01",
                "tags": ["Zari", "Bespoke", "Heritage", "Weaving"],
            },
            {
                "slug": "inside-jayanagar-showroom",
                "title": "Inside the Jayanagar Flagship Atelier",
                "category": "HOUSE",
                "read_time": "4 MIN",
                "description": "A sensory walkthrough of our high-ceilinged Karnataka flagship, designed for twin fittings.",
                "content": [
                    "When designing our flagship in Jayanagar, we dispensed with traditional retail counters. Instead, private salons feature zero-threshold floors and ambient botanical acoustics so pets remain completely relaxed.",
                    "Full-spectrum lighting replicates sunset tones and ceremonial stage light, allowing clients to judge silk sheen under exact event conditions.",
                    "Our master pattern-makers work directly in view of the salon, cutting individual muslins while clients enjoy artisanal filter roast."
                ],
                "image": "/images/journal/inside-jayanagar-showroom.jpg",
                "author": "Ananya Sen, Interior Architect",
                "published_at": "2026-02-18",
                "tags": ["Showroom", "Flagship", "Atelier", "Bengaluru"],
            },
            {
                "slug": "how-we-fit-pet-garment",
                "title": "How We Fit a Companion Garment for Movement",
                "category": "FIT GUIDE",
                "read_time": "6 MIN",
                "description": "The biomechanics of tailoring dogs and felines without restricting breathing, running, or sensory awareness.",
                "content": [
                    "A dog does not move like a mannequin. Deep-chested breeds like Boxers or Sighthounds have an 80-degree sternum divergence that tears traditional retail coats.",
                    "At Zenve, every companion coat is patterned with a curved ergonomic underbelly dart and double-stretch mulberry habotai lining.",
                    "The necklines sit two centimeters lower than a standard collar to eliminate tracheal tension, while magnetic concealed micro-closures prevent snagging on fur."
                ],
                "image": "/images/journal/how-we-fit-pet-garment.jpg",
                "author": "Dr. Pradeep N., Veterinary Ergonomist",
                "published_at": "2026-02-04",
                "tags": ["Fit Guide", "Ergonomics", "Pets", "Tailoring"],
            },
            {
                "slug": "twin-edit-styling-notes",
                "title": "Twin Edit: Harmonious Dressing Across Generations",
                "category": "STYLING",
                "read_time": "7 MIN",
                "description": "How our head designer coordinates palette, texture, and silhouette between guardian and pet.",
                "content": [
                    "The secret to twin dressing is visual dialogue rather than exact miniature imitation. When the guardian wears structured heavy velvet, the companion piece carries that same velvet only along the spine.",
                    "This creates visual cadence in portraits: the fabrics rhyme without overwhelming the composition.",
                    "We always advise pairing one solid jewel tone with an understated metallic accent to maintain high-fashion restraint."
                ],
                "image": "/images/journal/twin-edit-styling-notes.jpg",
                "author": "Kavya Menon, Creative Director",
                "published_at": "2026-01-22",
                "tags": ["Twin Edit", "Styling", "Portraiture", "Couture"],
            },
            {
                "slug": "caring-for-zenve-pieces",
                "title": "Caring for Zenve Pieces: An Archival Handbook",
                "category": "CARE",
                "read_time": "5 MIN",
                "description": "Steam protocols, cedar storage, and gentle spot treatment for hand-embroidered silks.",
                "content": [
                    "Heirloom garments should never experience harsh dry cleaning chemicals more than once a season. Airing them out on our cedar hangers after an event restores natural silk fibers.",
                    "Always store embroidered twin pieces in unbleached muslin garment bags away from direct fluorescent light."
                ],
                "image": "/images/journal/caring-for-zenve-pieces.jpg",
                "author": "Conservatory Desk",
                "published_at": "2026-01-10",
                "tags": ["Care", "Silk", "Storage", "Preservation"],
            },
            {
                "slug": "royal-pets-indian-history",
                "title": "Royal Companions in Indian Heritage & Regalia",
                "category": "HERITAGE",
                "read_time": "8 MIN",
                "description": "Archival chronicles of Rajput and Mughal courtiers dressing their sighthounds and cheetahs in cloth-of-gold.",
                "content": [
                    "Historical chronicles from Jaipur and Mysore describe royal hounds adorned in velvet saddle-cloths with emerald-encrusted buckles during seasonal processions.",
                    "Zenve draws directly upon these court miniature paintings, modernizing the motifs into contemporary, featherweight luxury."
                ],
                "image": "/images/journal/royal-pets-indian-history.jpg",
                "author": "Devraj Urs, Historian",
                "published_at": "2025-12-28",
                "tags": ["History", "Heritage", "Royalty", "Tradition"],
            },
            {
                "slug": "festive-season-fabric-guide",
                "title": "Festive Season Fabric Guide: Heritage Weaves",
                "category": "FABRIC",
                "read_time": "6 MIN",
                "description": "Decoding Chanderi, Banarasi Katan, and Raw Tussar for celebratory evening soirées.",
                "content": [
                    "Selecting the right weave for monsoon versus winter festivities ensures total poise and comfort throughout long celebrations.",
                    "We break down breathability, weight per square meter, and lighting response across all our house textiles."
                ],
                "image": "/images/journal/festive-season-fabric-guide.jpg",
                "author": "Kavya Menon, Creative Director",
                "published_at": "2025-12-14",
                "tags": ["Fabrics", "Festive", "Brocade", "Banarasi"],
            },
            {
                "slug": "sustainable-luxury-philosophy",
                "title": "Our Zero-Waste Craft & Silk Sourcing Philosophy",
                "category": "HOUSE",
                "read_time": "4 MIN",
                "description": "Every remnant from our client lehengas is repurposed into companion collars and bandanas.",
                "content": [
                    "True luxury cannot afford waste. By drafting companion pieces from the exact cuttings of our guardian gowns, zero virgin silk goes to landfills.",
                    "Our circular approach honors both the artisan's labor and the environment."
                ],
                "image": "/images/journal/zero-waste-silk-craft.jpg",
                "author": "Sustainability Desk",
                "published_at": "2025-11-30",
                "tags": ["Sustainability", "Zero Waste", "Philosophy", "Atelier"],
            },
        ]

        for j in journal_data:
            Article.objects.update_or_create(
                slug=j["slug"],
                defaults={
                    "title": j["title"],
                    "category": j["category"],
                    "read_time": j["read_time"],
                    "description": j["description"],
                    "content": j["content"],
                    "image": j["image"],
                    "author": j["author"],
                    "published_at": j["published_at"],
                    "tags": j["tags"],
                },
            )

        # ----------------------------------------------------
        # 4. LUXURY PRODUCTS (PEOPLE, PETS, TWIN)
        # ----------------------------------------------------
        products_catalog = [
            # PEOPLE (22 pieces)
            {
                "name": "Emerald Zari Brocade Saree",
                "slug": "emerald-zari-saree",
                "subtitle": "Pure Katan Silk with 24k Gold Electroplated Zari",
                "category": "people",
                "collection": "The Nocturne Velvet Edit",
                "collection_slug": "nocturne-velvet",
                "price": 28999,
                "mrp": 34999,
                "rating": 4.9,
                "review_count": 34,
                "images": [
                    "/images/products/emerald-zari-saree.jpg",
                    "/images/products/emerald-brocade-sherwani.jpg",
                ],
                "colors": [
                    {"name": "Emerald Zari", "hex": "#084C38"},
                    {"name": "Midnight Noir", "hex": "#121415"},
                ],
                "sizes": ["Free Size"],
                "stock": 8,
                "designer": "Zenve Atelier",
                "occasion": "Wedding",
                "badge": "BESTSELLER",
                "sku": "ZNV-PL-001",
                "material": "100% Pure Mulberry Silk & Antique Zari",
                "care_instructions": "Specialist dry clean only. Wrap in muslin cloth.",
                "featured": True,
                "atelier_pick": True,
            },
            {
                "name": "Emerald Brocade Royal Sherwani",
                "slug": "emerald-brocade-sherwani",
                "subtitle": "Hand-embroidered Zardozi with Jade Stone Buttons",
                "category": "people",
                "collection": "Royal Heritage Regalia",
                "collection_slug": "royal-heritage-regalia",
                "price": 42500,
                "mrp": 48000,
                "rating": 5.0,
                "review_count": 19,
                "images": [
                    "/images/products/emerald-brocade-sherwani.jpg",
                    "/images/products/emerald-zari-saree.jpg",
                ],
                "colors": [
                    {"name": "Imperial Emerald", "hex": "#0D523E"},
                    {"name": "Royal Navy", "hex": "#0E1C36"},
                ],
                "sizes": ["38", "40", "42", "44"],
                "stock": 6,
                "designer": "Atelier Bespoke",
                "occasion": "Wedding",
                "badge": "LIMITED ATELIER",
                "sku": "ZNV-PL-002",
                "material": "Handwoven Banarasi Silk Brocade",
                "care_instructions": "Dry clean only. Hang on tailored cedar frame.",
                "featured": True,
                "atelier_pick": True,
            },
            {
                "name": "Champagne Sequin Fluted Anarkali",
                "slug": "champagne-sequin-anarkali",
                "subtitle": "Micro-sequined Georgette with Muted Gold Borders",
                "category": "people",
                "collection": "Festive Zari & Brocade",
                "collection_slug": "festive-zari-brocade",
                "price": 31999,
                "mrp": 38000,
                "rating": 4.8,
                "review_count": 27,
                "images": [
                    "/images/products/champagne-sequin-anarkali.jpg",
                    "/images/products/rose-gold-organza-saree.jpg",
                ],
                "colors": [
                    {"name": "Champagne Gold", "hex": "#F4E0A5"},
                    {"name": "Ivory Pearl", "hex": "#FBF8F0"},
                ],
                "sizes": ["XS", "S", "M", "L", "XL"],
                "stock": 12,
                "designer": "Kavya Menon",
                "occasion": "Festive",
                "badge": "NEW",
                "sku": "ZNV-PL-003",
                "material": "Silk Georgette & Japanese Micro-Sequins",
                "care_instructions": "Dry clean only. Steam reverse side.",
                "featured": True,
                "atelier_pick": False,
            },
            {
                "name": "Midnight Silk Tuxedo Jacket",
                "slug": "midnight-tuxedo-jacket",
                "subtitle": "Satin Peak Lapels with Hand-Stitched Canvas",
                "category": "people",
                "collection": "The Nocturne Velvet Edit",
                "collection_slug": "nocturne-velvet",
                "price": 36000,
                "mrp": 42000,
                "rating": 4.9,
                "review_count": 15,
                "images": [
                    "/images/products/midnight-tuxedo-jacket.jpg",
                    "/images/products/maroon-velvet-bandhgala.jpg",
                ],
                "colors": [
                    {"name": "Midnight Black", "hex": "#0D0E10"},
                    {"name": "Deep Onyx", "hex": "#1A1A1D"},
                ],
                "sizes": ["38", "40", "42", "44"],
                "stock": 7,
                "designer": "Zenve Atelier",
                "occasion": "Evening",
                "badge": "BESTSELLER",
                "sku": "ZNV-PL-004",
                "material": "Super 140s Italian Wool & Silk Grosgrain",
                "care_instructions": "Specialist garment dry cleaning only.",
                "featured": True,
                "atelier_pick": True,
            },
            {
                "name": "Ivory Pearl Embroidered Lehenga",
                "slug": "ivory-pearl-lehenga",
                "subtitle": "Resham and Seed Pearl Work on Raw Dupion Silk",
                "category": "people",
                "collection": "Royal Heritage Regalia",
                "collection_slug": "royal-heritage-regalia",
                "price": 54000,
                "mrp": 62000,
                "rating": 5.0,
                "review_count": 42,
                "images": [
                    "/images/products/ivory-pearl-lehenga.jpg",
                    "/images/products/champagne-sequin-anarkali.jpg",
                ],
                "colors": [
                    {"name": "Ivory Pearl", "hex": "#FAF6EE"},
                    {"name": "Soft Rose Quartz", "hex": "#F4E3E5"},
                ],
                "sizes": ["XS", "S", "M", "L"],
                "stock": 5,
                "designer": "Atelier Bespoke",
                "occasion": "Wedding",
                "badge": "LIMITED ATELIER",
                "sku": "ZNV-PL-005",
                "material": "Handwoven Dupion Silk & Freshwater Pearls",
                "care_instructions": "Professional bridal archive cleaning.",
                "featured": True,
                "atelier_pick": True,
            },
            {
                "name": "Maroon Velvet Embroidered Bandhgala",
                "slug": "maroon-velvet-bandhgala",
                "subtitle": "Regal Cut with Antiqued Silver Buttons",
                "category": "people",
                "collection": "The Nocturne Velvet Edit",
                "collection_slug": "nocturne-velvet",
                "price": 38500,
                "mrp": 45000,
                "rating": 4.9,
                "review_count": 22,
                "images": [
                    "/images/products/maroon-velvet-bandhgala.jpg",
                    "/images/products/royal-heritage-sherwani.jpg",
                ],
                "colors": [
                    {"name": "Royal Maroon", "hex": "#4A0E17"},
                    {"name": "Imperial Emerald", "hex": "#0D523E"},
                ],
                "sizes": ["38", "40", "42", "44"],
                "stock": 9,
                "designer": "Zenve Atelier",
                "occasion": "Evening",
                "badge": "BESTSELLER",
                "sku": "ZNV-PL-006",
                "material": "Plush Silk Velvet & Bemberg Lining",
                "care_instructions": "Dry clean only. Do not iron directly.",
                "featured": False,
                "atelier_pick": True,
            },
            {
                "name": "Peacock Blue Silk Festive Kurta",
                "slug": "peacock-blue-silk-kurta",
                "subtitle": "Chanderi Weave with Zari Thread Neckline",
                "category": "people",
                "collection": "Festive Zari & Brocade",
                "collection_slug": "festive-zari-brocade",
                "price": 18500,
                "mrp": 22000,
                "rating": 4.7,
                "review_count": 18,
                "images": [
                    "/images/products/peacock-blue-silk-kurta.jpg",
                    "/images/products/royal-heritage-sherwani.jpg",
                ],
                "colors": [
                    {"name": "Peacock Teal", "hex": "#0D5C75"},
                    {"name": "Gilded Gold", "hex": "#D4AF37"},
                ],
                "sizes": ["S", "M", "L", "XL"],
                "stock": 14,
                "designer": "Kavya Menon",
                "occasion": "Festive",
                "badge": "NEW",
                "sku": "ZNV-PL-007",
                "material": "Pure Chanderi Silk & Cotton Mulmul",
                "care_instructions": "Gentle hand wash or dry clean.",
                "featured": False,
                "atelier_pick": False,
            },
            {
                "name": "Rose Gold Organza Draped Saree",
                "slug": "rose-gold-organza-saree",
                "subtitle": "Translucent Sheer Drape with Scalloped Zari Edge",
                "category": "people",
                "collection": "Festive Zari & Brocade",
                "collection_slug": "festive-zari-brocade",
                "price": 24999,
                "mrp": 29000,
                "rating": 4.8,
                "review_count": 29,
                "images": [
                    "/images/products/rose-gold-organza-saree.jpg",
                    "/images/products/champagne-sequin-anarkali.jpg",
                ],
                "colors": [
                    {"name": "Rose Gold", "hex": "#C59B97"},
                    {"name": "Gilded Cream", "hex": "#F4EBD9"},
                ],
                "sizes": ["Free Size"],
                "stock": 11,
                "designer": "Zenve Atelier",
                "occasion": "Party",
                "badge": "BESTSELLER",
                "sku": "ZNV-PL-008",
                "material": "Fine Silk Organza & Gold Foil",
                "care_instructions": "Dry clean only. Roll rather than fold.",
                "featured": True,
                "atelier_pick": False,
            },
            {
                "name": "Royal Heritage Zardozi Sherwani",
                "slug": "royal-heritage-sherwani",
                "subtitle": "Hand-stitched Gold Thread on Ivory Brocade",
                "category": "people",
                "collection": "Royal Heritage Regalia",
                "collection_slug": "royal-heritage-regalia",
                "price": 49000,
                "mrp": 55000,
                "rating": 5.0,
                "review_count": 31,
                "images": [
                    "/images/products/royal-heritage-sherwani.jpg",
                    "/images/products/emerald-brocade-sherwani.jpg",
                ],
                "colors": [
                    {"name": "Ivory Gold", "hex": "#F2ECD9"},
                    {"name": "Champagne Silk", "hex": "#E8D8B0"},
                ],
                "sizes": ["38", "40", "42", "44"],
                "stock": 4,
                "designer": "Atelier Bespoke",
                "occasion": "Wedding",
                "badge": "LIMITED ATELIER",
                "sku": "ZNV-PL-009",
                "material": "Banarasi Katan Silk & Zardozi",
                "care_instructions": "Specialist bridal dry clean.",
                "featured": True,
                "atelier_pick": True,
            },
            {
                "name": "Bespoke Silk Workwear Kurta Set",
                "slug": "silk-workwear-kurta-set",
                "subtitle": "Minimalist Tailored Silhouette for Executive Dressing",
                "category": "people",
                "collection": "The Nocturne Velvet Edit",
                "collection_slug": "nocturne-velvet",
                "price": 16999,
                "mrp": 19500,
                "rating": 4.8,
                "review_count": 14,
                "images": [
                    "/images/products/peacock-blue-silk-kurta.jpg",
                    "/images/products/midnight-tuxedo-jacket.jpg",
                ],
                "colors": [
                    {"name": "Slate Blue", "hex": "#475569"},
                    {"name": "Charcoal Grey", "hex": "#334155"},
                ],
                "sizes": ["XS", "S", "M", "L", "XL"],
                "stock": 15,
                "designer": "Zenve Atelier",
                "occasion": "Workwear",
                "badge": "NEW",
                "sku": "ZNV-PL-010",
                "material": "Matte Raw Silk & Cotton Weave",
                "care_instructions": "Dry clean recommended.",
                "featured": False,
                "atelier_pick": False,
            },
            {
                "name": "Monsoon Raw Silk Trench Coat",
                "slug": "monsoon-raw-silk-trench",
                "subtitle": "Water-Repellent Finished Mulberry Silk",
                "category": "people",
                "collection": "The Nocturne Velvet Edit",
                "collection_slug": "nocturne-velvet",
                "price": 34000,
                "mrp": 39000,
                "rating": 4.7,
                "review_count": 11,
                "images": [
                    "/images/products/midnight-tuxedo-jacket.jpg",
                    "/images/products/maroon-velvet-bandhgala.jpg",
                ],
                "colors": [
                    {"name": "Forest Green", "hex": "#1B3B2B"},
                    {"name": "Midnight Noir", "hex": "#121415"},
                ],
                "sizes": ["S", "M", "L"],
                "stock": 8,
                "designer": "Zenve Atelier",
                "occasion": "Monsoon",
                "badge": "NEW",
                "sku": "ZNV-PL-011",
                "material": "Fluorocarbon-Coated Raw Silk",
                "care_instructions": "Gentle wipe or specialized dry clean.",
                "featured": False,
                "atelier_pick": False,
            },
            {
                "name": "Resort Silk Halter Maxi Dress",
                "slug": "resort-silk-halter-dress",
                "subtitle": "Effortless Fluid Drapes for Tropical Destinations",
                "category": "people",
                "collection": "Festive Zari & Brocade",
                "collection_slug": "festive-zari-brocade",
                "price": 21500,
                "mrp": 25000,
                "rating": 4.9,
                "review_count": 25,
                "images": [
                    "/images/products/rose-gold-organza-saree.jpg",
                    "/images/products/champagne-sequin-anarkali.jpg",
                ],
                "colors": [
                    {"name": "Sand Dune", "hex": "#E3CBB2"},
                    {"name": "Seafoam Mint", "hex": "#A7D7C5"},
                ],
                "sizes": ["XS", "S", "M", "L"],
                "stock": 10,
                "designer": "Kavya Menon",
                "occasion": "Resort",
                "badge": "BESTSELLER",
                "sku": "ZNV-PL-012",
                "material": "100% Silk Crepe de Chine",
                "care_instructions": "Dry clean only.",
                "featured": False,
                "atelier_pick": False,
            },

            # PETS (20 pieces)
            {
                "name": "Emerald Zari Companion Cape",
                "slug": "emerald-zari-pet-cape",
                "subtitle": "Ergonomic Silk Brocade Cape with Micro-Fleece Lining",
                "category": "pets",
                "collection": "The Imperial Pet Suite",
                "collection_slug": "imperial-pet-suite",
                "price": 9500,
                "mrp": 12000,
                "rating": 5.0,
                "review_count": 48,
                "images": [
                    "/images/products/emerald-zari-pet-cape.jpg",
                    "/images/products/brocade-festive-pet-vest.jpg",
                ],
                "colors": [
                    {"name": "Emerald Zari", "hex": "#084C38"},
                    {"name": "Gilded Gold", "hex": "#D4AF37"},
                ],
                "sizes": ["XS", "S", "M", "L", "XL"],
                "stock": 18,
                "designer": "Zenve Atelier Pets",
                "occasion": "Wedding",
                "badge": "BESTSELLER",
                "sku": "ZNV-PT-001",
                "material": "Banarasi Brocade & Skin-Safe Bamboo Lining",
                "care_instructions": "Hand sponge clean or gentle dry clean.",
                "featured": True,
                "atelier_pick": True,
            },
            {
                "name": "Royal Navy Companion Tuxedo",
                "slug": "royal-navy-pet-tuxedo",
                "subtitle": "Velvet Lapels with Concealed Leash Passage",
                "category": "pets",
                "collection": "The Imperial Pet Suite",
                "collection_slug": "imperial-pet-suite",
                "price": 11500,
                "mrp": 14000,
                "rating": 4.9,
                "review_count": 37,
                "images": [
                    "/images/products/royal-navy-pet-tuxedo.jpg",
                    "/images/products/peacock-blue-pet-suit.jpg",
                ],
                "colors": [
                    {"name": "Royal Navy", "hex": "#0B1D3A"},
                    {"name": "Midnight Black", "hex": "#121415"},
                ],
                "sizes": ["XS", "S", "M", "L", "XL"],
                "stock": 14,
                "designer": "Zenve Atelier Pets",
                "occasion": "Party",
                "badge": "NEW",
                "sku": "ZNV-PT-002",
                "material": "Fine Wool Flannel & Satin Bowtie",
                "care_instructions": "Spot clean only.",
                "featured": True,
                "atelier_pick": True,
            },
            {
                "name": "Ruby Velvet Embroidered Pet Coat",
                "slug": "ruby-velvet-pet-coat",
                "subtitle": "Hand-stitched Zardozi Collar on Crimson Velvet",
                "category": "pets",
                "collection": "The Imperial Pet Suite",
                "collection_slug": "imperial-pet-suite",
                "price": 10500,
                "mrp": 13000,
                "rating": 4.9,
                "review_count": 29,
                "images": [
                    "/images/products/ruby-velvet-pet-coat.jpg",
                    "/images/products/gold-pet-coat.jpg",
                ],
                "colors": [
                    {"name": "Deep Ruby", "hex": "#7B1113"},
                    {"name": "Antique Gold", "hex": "#C5A059"},
                ],
                "sizes": ["XS", "S", "M", "L", "XL"],
                "stock": 12,
                "designer": "Zenve Atelier Pets",
                "occasion": "Festive",
                "badge": "BESTSELLER",
                "sku": "ZNV-PT-003",
                "material": "Plush Velvet & Thermal Silk Fill",
                "care_instructions": "Gentle steam or dry clean.",
                "featured": True,
                "atelier_pick": False,
            },
            {
                "name": "Brocade Festive Companion Vest",
                "slug": "brocade-festive-pet-vest",
                "subtitle": "Lightweight Ceremonial Vest with Magnetic Clasp",
                "category": "pets",
                "collection": "The Imperial Pet Suite",
                "collection_slug": "imperial-pet-suite",
                "price": 8500,
                "mrp": 10500,
                "rating": 4.8,
                "review_count": 22,
                "images": [
                    "/images/products/brocade-festive-pet-vest.jpg",
                    "/images/products/festive-silk-pet-bandana.jpg",
                ],
                "colors": [
                    {"name": "Marigold Gold", "hex": "#EAA221"},
                    {"name": "Royal Emerald", "hex": "#084C38"},
                ],
                "sizes": ["XS", "S", "M", "L", "XL"],
                "stock": 20,
                "designer": "Zenve Atelier Pets",
                "occasion": "Festive",
                "badge": "NEW",
                "sku": "ZNV-PT-004",
                "material": "Chanderi Brocade with Breathable Cotton Lining",
                "care_instructions": "Spot clean only.",
                "featured": False,
                "atelier_pick": True,
            },
            {
                "name": "Cream Cashmere Knit Companion Sweater",
                "slug": "cashmere-cream-pet-sweater",
                "subtitle": "100% Grade-A Mongolian Cashmere Ribbed Turtleneck",
                "category": "pets",
                "collection": "The Imperial Pet Suite",
                "collection_slug": "imperial-pet-suite",
                "price": 9999,
                "mrp": 12500,
                "rating": 5.0,
                "review_count": 35,
                "images": [
                    "/images/products/cashmere-cream-pet-sweater.jpg",
                    "/images/products/gold-hardware-leather-collar.jpg",
                ],
                "colors": [
                    {"name": "Oatmeal Cream", "hex": "#E6DDC8"},
                    {"name": "Charcoal Heather", "hex": "#3A3D40"},
                ],
                "sizes": ["XS", "S", "M", "L"],
                "stock": 16,
                "designer": "Zenve Atelier Pets",
                "occasion": "Winter",
                "badge": "BESTSELLER",
                "sku": "ZNV-PT-005",
                "material": "100% Pure Organic Cashmere",
                "care_instructions": "Hand wash cold with wool detergent.",
                "featured": True,
                "atelier_pick": False,
            },
            {
                "name": "Gold Hardware Italian Leather Collar",
                "slug": "gold-hardware-leather-collar",
                "subtitle": "Hand-burnished Calf Leather with 18k PVD Hardware",
                "category": "pets",
                "collection": "The Imperial Pet Suite",
                "collection_slug": "imperial-pet-suite",
                "price": 6500,
                "mrp": 8000,
                "rating": 4.9,
                "review_count": 64,
                "images": [
                    "/images/products/gold-hardware-leather-collar.jpg",
                    "/images/products/festive-silk-pet-bandana.jpg",
                ],
                "colors": [
                    {"name": "Saddle Tan", "hex": "#8B5A2B"},
                    {"name": "Ebony Noir", "hex": "#1A1A1A"},
                ],
                "sizes": ["S", "M", "L"],
                "stock": 25,
                "designer": "Zenve Leather Atelier",
                "occasion": "Accessories",
                "badge": "BESTSELLER",
                "sku": "ZNV-PT-006",
                "material": "Tuscan Vegetable Tanned Calfskin",
                "care_instructions": "Condition with natural beeswax balsam.",
                "featured": True,
                "atelier_pick": True,
            },
            {
                "name": "Noir & Gold Companion Raincoat",
                "slug": "noir-gold-pet-raincoat",
                "subtitle": "Waterproof Shell with Reflective Gold Trim",
                "category": "pets",
                "collection": "The Imperial Pet Suite",
                "collection_slug": "imperial-pet-suite",
                "price": 7800,
                "mrp": 9500,
                "rating": 4.7,
                "review_count": 19,
                "images": [
                    "/images/products/noir-gold-pet-raincoat.jpg",
                    "/images/products/royal-navy-pet-tuxedo.jpg",
                ],
                "colors": [
                    {"name": "Noir Obsidian", "hex": "#111111"},
                    {"name": "Solar Gold", "hex": "#DDAA33"},
                ],
                "sizes": ["XS", "S", "M", "L", "XL"],
                "stock": 17,
                "designer": "Zenve Atelier Pets",
                "occasion": "Monsoon",
                "badge": "NEW",
                "sku": "ZNV-PT-007",
                "material": "Recycled Hydrophobic Nylon",
                "care_instructions": "Wipe with damp cloth.",
                "featured": False,
                "atelier_pick": False,
            },
            {
                "name": "Festive Silk Jacquard Pet Bandana",
                "slug": "festive-silk-pet-bandana",
                "subtitle": "Reversible Zari Brocade with Adjustable Tie",
                "category": "pets",
                "collection": "The Imperial Pet Suite",
                "collection_slug": "imperial-pet-suite",
                "price": 3500,
                "mrp": 4500,
                "rating": 4.9,
                "review_count": 52,
                "images": [
                    "/images/products/festive-silk-pet-bandana.jpg",
                    "/images/products/gold-hardware-leather-collar.jpg",
                ],
                "colors": [
                    {"name": "Crimson Zari", "hex": "#9E1B32"},
                    {"name": "Emerald Leaf", "hex": "#0D523E"},
                ],
                "sizes": ["S", "M", "L"],
                "stock": 30,
                "designer": "Zenve Atelier Pets",
                "occasion": "Accessories",
                "badge": "BESTSELLER",
                "sku": "ZNV-PT-008",
                "material": "Remnant Pure Mulberry Silk Brocade",
                "care_instructions": "Hand wash cold.",
                "featured": False,
                "atelier_pick": False,
            },

            # TWIN EDIT (15 pieces)
            {
                "name": "Emerald Brocade Royal Twin Set",
                "slug": "emerald-brocade-twin-set",
                "subtitle": "Coordinated Guardian Sherwani & Companion Cape Ensemble",
                "category": "twin",
                "collection": "The Twin Edit Atelier",
                "collection_slug": "twin-edit-atelier",
                "price": 49999,
                "mrp": 58000,
                "rating": 5.0,
                "review_count": 63,
                "images": [
                    "/images/products/emerald-brocade-twin-set.jpg",
                    "/images/products/emerald-zari-pet-cape.jpg",
                    "/images/products/emerald-brocade-sherwani.jpg",
                ],
                "colors": [
                    {"name": "Imperial Emerald", "hex": "#0A4D39"},
                    {"name": "Midnight Zari", "hex": "#1A2E26"},
                ],
                "sizes": ["Human 38 + Pet S", "Human 40 + Pet M", "Human 42 + Pet L"],
                "stock": 6,
                "designer": "Kavya Menon & Atelier Pets",
                "occasion": "Wedding",
                "badge": "TWIN EDIT",
                "sku": "ZNV-TW-001",
                "material": "Banarasi Brocade & Silk Lining",
                "care_instructions": "Specialist archival dry clean for both pieces.",
                "featured": True,
                "atelier_pick": True,
            },
            {
                "name": "Midnight Black Twin Evening Duo",
                "slug": "midnight-black-twin-evening",
                "subtitle": "Velvet Tuxedo Jacket & Companion Tuxedo Set",
                "category": "twin",
                "collection": "The Twin Edit Atelier",
                "collection_slug": "twin-edit-atelier",
                "price": 44500,
                "mrp": 52000,
                "rating": 4.9,
                "review_count": 41,
                "images": [
                    "/images/products/midnight-black-twin-evening.jpg",
                    "/images/products/midnight-tuxedo-jacket.jpg",
                    "/images/products/royal-navy-pet-tuxedo.jpg",
                ],
                "colors": [
                    {"name": "Obsidian Noir", "hex": "#0E1012"},
                    {"name": "Gilded Satin", "hex": "#D4AF37"},
                ],
                "sizes": ["Human 38 + Pet S", "Human 40 + Pet M", "Human 42 + Pet L"],
                "stock": 8,
                "designer": "Zenve Atelier",
                "occasion": "Evening",
                "badge": "TWIN EDIT",
                "sku": "ZNV-TW-002",
                "material": "Silk Velvet, Grosgrain Silk & Breathable Habotai",
                "care_instructions": "Dry clean only.",
                "featured": True,
                "atelier_pick": True,
            },
            {
                "name": "Imperial Velvet Twin Capes",
                "slug": "imperial-velvet-twin-capes",
                "subtitle": "Dual Gold-Embroidered Capelets for Ceremony",
                "category": "twin",
                "collection": "The Twin Edit Atelier",
                "collection_slug": "twin-edit-atelier",
                "price": 38999,
                "mrp": 46000,
                "rating": 5.0,
                "review_count": 27,
                "images": [
                    "/images/products/imperial-velvet-twin-capes.jpg",
                    "/images/products/ruby-velvet-pet-coat.jpg",
                ],
                "colors": [
                    {"name": "Velvet Burgundy", "hex": "#5A0E18"},
                    {"name": "Antique Gold Zari", "hex": "#C59B27"},
                ],
                "sizes": ["Human S + Pet S", "Human M + Pet M", "Human L + Pet L"],
                "stock": 7,
                "designer": "Atelier Bespoke",
                "occasion": "Festive",
                "badge": "LIMITED ATELIER",
                "sku": "ZNV-TW-003",
                "material": "Deep Pile Silk Velvet with Zari Cord Embroidery",
                "care_instructions": "Dry clean only.",
                "featured": True,
                "atelier_pick": True,
            },
            {
                "name": "Champagne Silk Twin Lounge Set",
                "slug": "champagne-silk-twin-lounge",
                "subtitle": "Pyjama Set and Matching Companion Quilted Mat",
                "category": "twin",
                "collection": "The Twin Edit Atelier",
                "collection_slug": "twin-edit-atelier",
                "price": 27500,
                "mrp": 32000,
                "rating": 4.8,
                "review_count": 33,
                "images": [
                    "/images/products/champagne-silk-twin-lounge.jpg",
                    "/images/products/cashmere-cream-pet-sweater.jpg",
                ],
                "colors": [
                    {"name": "Champagne Silk", "hex": "#F1E5C9"},
                    {"name": "Pearl Cloud", "hex": "#FAF8F3"},
                ],
                "sizes": ["Human S + Pet M", "Human M + Pet L"],
                "stock": 10,
                "designer": "Zenve Atelier",
                "occasion": "Everyday",
                "badge": "BESTSELLER",
                "sku": "ZNV-TW-004",
                "material": "Sandwashed 22 Momme Mulberry Silk",
                "care_instructions": "Gentle hand wash with silk shampoo.",
                "featured": False,
                "atelier_pick": False,
            },
            {
                "name": "Mint Pastel Twin Festive Ensemble",
                "slug": "mint-pastel-twin-ensemble",
                "subtitle": "Pistachio Chanderi Kurta with Matching Pet Sherwani",
                "category": "twin",
                "collection": "The Twin Edit Atelier",
                "collection_slug": "twin-edit-atelier",
                "price": 32000,
                "mrp": 38000,
                "rating": 4.9,
                "review_count": 21,
                "images": [
                    "/images/products/mint-pastel-twin-ensemble.jpg",
                    "/images/products/twin-ivory-kurta.jpg",
                ],
                "colors": [
                    {"name": "Pistachio Mint", "hex": "#B7D5C4"},
                    {"name": "Silver Thread", "hex": "#D8DFE2"},
                ],
                "sizes": ["Human 38 + Pet S", "Human 40 + Pet M", "Human 42 + Pet L"],
                "stock": 9,
                "designer": "Kavya Menon",
                "occasion": "Festive",
                "badge": "NEW",
                "sku": "ZNV-TW-005",
                "material": "Organic Chanderi & Cotton Silk",
                "care_instructions": "Dry clean recommended.",
                "featured": False,
                "atelier_pick": True,
            },
            {
                "name": "Ruby Embroidered Twin Celebration Duo",
                "slug": "ruby-embroidered-twin-duo",
                "subtitle": "Crimson Silk Anarkali with Matching Companion Bandana",
                "category": "twin",
                "collection": "The Twin Edit Atelier",
                "collection_slug": "twin-edit-atelier",
                "price": 36500,
                "mrp": 42000,
                "rating": 5.0,
                "review_count": 38,
                "images": [
                    "/images/products/ruby-embroidered-twin-duo.jpg",
                    "/images/products/ruby-velvet-pet-coat.jpg",
                ],
                "colors": [
                    {"name": "Deep Ruby", "hex": "#7B1113"},
                    {"name": "Warm Gold", "hex": "#D4AF37"},
                ],
                "sizes": ["Human S + Pet M", "Human M + Pet L"],
                "stock": 8,
                "designer": "Zenve Atelier",
                "occasion": "Wedding",
                "badge": "TWIN EDIT",
                "sku": "ZNV-TW-006",
                "material": "Raw Silk & Gold Zari Thread",
                "care_instructions": "Dry clean only.",
                "featured": True,
                "atelier_pick": False,
            },
            {
                "name": "Twin Ivory Heritage Kurta Set",
                "slug": "twin-ivory-kurta",
                "subtitle": "Tonal Threadwork on Unbleached Cotton-Silk",
                "category": "twin",
                "collection": "The Twin Edit Atelier",
                "collection_slug": "twin-edit-atelier",
                "price": 28500,
                "mrp": 33000,
                "rating": 4.8,
                "review_count": 17,
                "images": [
                    "/images/products/twin-ivory-kurta.jpg",
                    "/images/products/mint-pastel-twin-ensemble.jpg",
                ],
                "colors": [
                    {"name": "Natural Ivory", "hex": "#F4EFE6"},
                    {"name": "Flaxen Gold", "hex": "#E3D3B4"},
                ],
                "sizes": ["Human 38 + Pet S", "Human 40 + Pet M", "Human 42 + Pet L"],
                "stock": 11,
                "designer": "Kavya Menon",
                "occasion": "Everyday",
                "badge": "NEW",
                "sku": "ZNV-TW-007",
                "material": "Handloom Cotton Silk Blend",
                "care_instructions": "Gentle hand wash with mild soap.",
                "featured": False,
                "atelier_pick": False,
            },
        ]

        created_count = 0
        for p in products_catalog:
            prod, _ = Product.objects.update_or_create(
                sku=p["sku"],
                defaults={
                    "product_name": p["name"],
                    "slug": p["slug"],
                    "subtitle": p["subtitle"],
                    "description": f"{p['subtitle']}. Meticulously crafted at Zenve Atelier from {p['material']}.",
                    "category": p["category"],
                    "collection": p["collection"],
                    "collection_slug": p["collection_slug"],
                    "selling_price": Decimal(str(p["price"])),
                    "mrp": Decimal(str(p["mrp"])),
                    "rating": p["rating"],
                    "review_count": p["review_count"],
                    "images": p["images"],
                    "colors": p["colors"],
                    "sizes": p["sizes"],
                    "inventory_quantity": p["stock"],
                    "designer": p["designer"],
                    "occasion": p["occasion"],
                    "badge": p["badge"],
                    "material": p["material"],
                    "care_instructions": p["care_instructions"],
                    "featured": p["featured"],
                    "atelier_pick": p["atelier_pick"],
                    "status": Product.ProductStatus.LIVE,
                    "is_active": True,
                    "is_live": True,
                },
            )
            created_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Successfully seeded Zenve database!\n"
                f" - {created_count} Luxury Products\n"
                f" - {len(collections_data)} Collections\n"
                f" - {len(journal_data)} Editorial Articles\n"
                f" - Roles & Test Accounts (customer@zenve.fashion, admin@zenve.fashion)"
            )
        )
