# Generated by Django 6.1.1 on 2026-09-10 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id_string',
            field=models.CharField(blank=True, default='guest', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery',
            field=models.CharField(blank=True, default='3-5 Business Days', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
